# Generated by Django 2.2 on 2022-02-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accounts',
        ),
    ]
