# Generated by Django 2.2 on 2022-01-26 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
